from datetime import datetime

from pydantic import BaseModel, field_validator

from federation_hub_service.version_utils import parse_version


class InstallationRegister(BaseModel):
    id: str
    display_name: str
    callback_base_url: str
    public_key_pem: str
    version: str
    min_compatible_peer_version: str
    supported_process_types: list[str] = []
    supported_document_types: list[str] = []

    @field_validator("version", "min_compatible_peer_version")
    @classmethod
    def _validate_version_format(cls, value: str) -> str:
        """P13-S3 finding: without this check, registration accepted any
        string without complaint - an invalid format only surfaced later,
        during a completely unrelated `POST /handovers` mediation, as an
        unhandled `ValueError` (500), see `version_utils.py`."""
        parse_version(value)
        return value


class InstallationOut(BaseModel):
    id: str
    display_name: str
    callback_base_url: str
    public_key_pem: str
    version: str
    min_compatible_peer_version: str
    supported_process_types: list[str]
    supported_document_types: list[str]
    registered_at: datetime
    updated_at: datetime
    revoked_at: datetime | None = None
    revoked_reason: str | None = None
    # Since Post-Roadmap Phase 21 Session 2 (ADR 0085) - not secret (contains
    # only the already-public key + hub signature), so it's safe to include
    # in output, unlike a private key/API key.
    certificate_pem: str | None = None
    certificate_not_after: datetime | None = None

    model_config = {"from_attributes": True}


class RotateKeyRequest(BaseModel):
    new_public_key_pem: str


class RevokeRequest(BaseModel):
    reason: str | None = None


class HandoverCreate(BaseModel):
    # Generated by the sending installation itself (not by the hub) - see
    # ADR 0028 "self-loopback": the installation must already have committed
    # its own, local `FederationTask` row before calling the hub (which can
    # deliver synchronously back into the same installation), otherwise the
    # row wouldn't yet be visible on a nested callback (e.g. handover to the
    # same installation).
    handover_id: str
    to_installation_id: str
    process_type: str
    # Base64-encoded, end-to-end encrypted envelope JSON (see
    # `workflow_service.federation_crypto`) - fully opaque to the hub.
    encrypted_payload: str


class HandoverOut(BaseModel):
    id: str
    from_installation_id: str
    to_installation_id: str
    process_type: str
    status: str
    attempts: int
    next_retry_at: datetime | None
    created_at: datetime
    delivered_at: datetime | None
    completed_at: datetime | None

    model_config = {"from_attributes": True}


class HandoverResultSubmit(BaseModel):
    # "completed" (successfully completed from a business perspective) |
    # "failed" (target installation could not process the step) - purely
    # informational for the sending side, the hub itself does not evaluate
    # it.
    outcome: str
    encrypted_result: str


class PublicKeyOut(BaseModel):
    public_key_pem: str


class CaCertificateOut(BaseModel):
    ca_certificate_pem: str
